"""
viz_backend 모듈 단위 테스트.
"""
import pytest

pytest.importorskip("py3Dmol")

from qcviz_mcp.backends.registry import registry

@pytest.fixture
def viz_backend():
    return registry.get("py3dmol")

def test_render_molecule(viz_backend, sample_water_xyz):
    html = viz_backend.render_molecule(sample_water_xyz, style="stick")
    assert isinstance(html, str)
    assert "<script" in html
    assert "3Dmol" in html
    
    html_sphere = viz_backend.render_molecule(sample_water_xyz, style="sphere")
    assert "radius" not in html_sphere or "sphere" in html_sphere

def test_render_orbital(viz_backend, sample_water_xyz):
    # Dummy cube data
    dummy_cube = """CUBE FILE.
OUTER LOOP: X, MIDDLE LOOP: Y, INNER LOOP: Z
    3    0.000000    0.000000    0.000000
   10    0.100000    0.000000    0.000000
   10    0.000000    0.100000    0.000000
   10    0.000000    0.000000    0.100000
    8    8.000000    0.000000    0.000000    0.117300
    1    1.000000    0.000000    0.757200   -0.469200
    1    1.000000    0.000000   -0.757200   -0.469200
""" + "0.00000 " * 1000  # 최소한의 더미 데이터 채움
    
    html = viz_backend.render_orbital(
        xyz_data=sample_water_xyz,
        cube_data=dummy_cube,
        isovalue=0.02
    )
    assert "isoval" in html
    assert "0.02" in html

def test_render_orbital_from_cube(viz_backend, sample_water_xyz):
    """render_orbital_from_cube가 py3Dmol HTML을 생성하는지 확인."""
    fake_cube = """CUBE FILE generated by QCViz-MCP
OUTER LOOP: X, MIDDLE LOOP: Y, INNER LOOP: Z
    3    0.000000    0.000000    0.000000
   10    0.100000    0.000000    0.000000
   10    0.000000    0.100000    0.000000
   10    0.000000    0.000000    0.100000
    8    8.000000    0.000000    0.000000    0.117300
    1    1.000000    0.000000    0.757200   -0.469200
    1    1.000000    0.000000   -0.757200   -0.469200
""" + "0.00000 " * 1000

    html = viz_backend.render_orbital_from_cube(
        cube_text=fake_cube,
        geometry_xyz=sample_water_xyz,
        isovalue=0.05,
    )
    assert isinstance(html, str)
    assert "3Dmol" in html
    assert "addVolumetricData" in html
